### PR TITLE
Fix too few arguments in EventApplicationBridgeExtension

### PR DESCRIPTION
**Pull request by josefsabl**
Not sure if this meets the code style or whatever but it works for me :-)
https://github.com/contributte/event-dispatcher-extra/issues/15

### CODE REVIEW

**Comment by f3l1x** [comment]
Thank you. Could please also include some tests to prevent it for the future. It's undiscovered feature. :-)

**Comment by josefsabl** [comment]
I will put that to my TODO list. Maybe as some friday-fun project ;-) This was just quick fix through github interface. Thanks for this lib anyway!

**Comment by mabar** [comment]
@josefsabl Your issue is really weird for me. I tested our build once again and it works for me. I think php behavior changed between versions and no one noticed because it is very unusual use case.

Could you please test if other events works (eg. onPresenter would be enough) and provide me info about your environment? (OS, php version)

**Comment by f3l1x** [comment]
We've added more tests on it and it works. Feel free to open it again with more detailed information. Thank you anyway.

**Comment by josefsabl** [comment]
Well, I don't know. Ellipsis operator was introduced in PHP 5.6 and AFAIK there was no change that would break the functionality. It seems pretty straightforward and I believe this code (which is the essence of the problem) would not work in any version of PHP.

```PHP
$b = function ($foo) { //closure 1
	$a = function () { //closure 2
		var_dump(...func_get_args()); //var_dump
	};
	$a();
};

$b('foo');
```

The `func_get_args` relates to the function I marked as closure 2 which doesn't have any arguments thus the array is empty and ellipsis operator uniwinds it to "no arguments". So var_dump ends in `Wrong parameter count for var_dump()`.

The fix is:

```PHP
$b = function ($foo) { //closure 1
	$a = function () use ($foo) { //closure 2
		var_dump($foo); //var_dump
	};
	$a();
};

$b('foo');
```

The bug was in `onShutdown` and `onStartup` events which used the nested closure. Others are fine, I believe. The look like this.

```PHP
function ($foo) { //closure 1
    var_dump(...func_get_args()); //var_dump
}
```

The func_get_args now relates to closure 1 which has exactly one argument that gets unwind by ellipsis to one argument and that is what var_dump expects.

This is pretty tricky with all that magic (php code in a string, ? placeholders, magic func_get_args, magic ellipsis operator). The best way to debug was to look directly in the generated container code.

But anyway, I am on Windows 10 and my PHP is 7.2.4.

**Comment by f3l1x** [comment]
I think I get it, but the code looks like this:

```php
$application->onPresenter[] = function ($application, $presenter) {
	$presenter->onStartup[] = function (/** $presenter */) {
		var_dump(...func_get_args());
	};
};
```

And the trigger is in Presenter (https://api.nette.org/2.4/source-Application.UI.Presenter.php.html#186)

```php
public function run(Application\Request $request)
{
    // ....
    $this->onStartup($this);
   // ....
}
```

2nd closure receive current presenter object. Am I wrong?

**Comment by josefsabl** [comment]
Oh, I see. Unfortunately I don't remember when exactly I was getting the exception. I will just leave your version in the project and wait for the exception to re-appear :-)

**Comment by josefsabl** [comment]
Ok, I got it. The problem actually appears when combined with Arachne Security Verifier.

See [this piece of code](https://github.com/Arachne/Verifier/blob/1aad7cd228439cf84ee1f7cf35fd7ad578b9bc50/src/Application/VerifierPresenterTrait.php#L84) in Arachne.

It was discussed [here](https://github.com/Arachne/EntityLoader/issues/4) and closed as problem with Contributte.

**Pull request closed without merging**
